travis:
  secure:
    BINSTAR_TOKEN: r4diyrU3ZsZKHG7hgnJN/+oV3GTLMtES9bpzdSrKadXUdLJdM0JBExMo7tFtMlHt65bxAeHUyUG13l+7V59KSyfsRfp9D/XSdYzv4gPFRSsDVjzdm3GtWEZnMwHMEcfBSRkHRRUroUck/3VcYHEayts/OWkurLqGOr370PIvdeHI8We5/+o7wbBpTzM+gb1jLQcommudWSDc1WUSJWFcs41ZNz7BfRBoY27JsWJphZXf4oze8y7tm2FH+1ojDKLBLHBw/YKRnEE3bSS0TjE0cPT5sbuxy0u0atyIYdPZGosIZNwgIkDARg983WDRWhkulaUJdL1AR54uv9aTG/25PxpbsAKrBoFxVWr8u8ss5+8up33qoY+fVvQHu4RiSJ48GI0UE2meX9NcCUft4f075jG1kHJa4dz/AevKaJapw2l6GTICw06ePNP1xzwkNrKyjCJCQpSpL6A8zFH2gb7DcZFxKlNqaiqtefyeX9EntJqCy/7SzOgkQ0adV/SSTGDDbVjehmHjAJVo2ZnB7L6YlMtmSp5LBmZ3S7GE+3yx16VOWXRmvf/jOAVDPKYPX1rh59WmT9SdB37uTP1jPpRJ3GChJ5nxUy4d1mJeG0rss/OcaId4QTwR+mZM82WKMSj5TignDJBrjt4uUZFWJzP/kj/2L8bloDKfgZyVI7VEOAg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
