travis:
  secure:
    BINSTAR_TOKEN: wQYaX2+OEIahjhVxi86Es+NSKUcxG485uuFc+8yPAM6NQS56zlhtXWOWmd+MajljYAIuY5QEv7VHwOW87fdll0+sop6fJx+7PTVVeS8GrXIr5C5o8MhhdEuk4PCrLp2WxdyqWpV7uYlakehuUDXiRpX0k0Aa02+4cVtD1GHKA8rwumhMXPUxzivNmAsO5wPHJYYYJN39xmgDk0+pOmax0fB/1aYmA80NgL5kNmxm+kOrQEC3/Nni1/K5ekPa59xVF2rl82L8v7hSGf3Ig64N+BnuLh0fKS7jKTZjbvaObwjbByfWiiKo2NwPPmO48eUO/4n+u3MCaME8AIMUjcAor4todRyQEdnMR0FJ0/I3D3EYBauImpZJ7BRlHRNZFyrBsgGa6/U6WSSJfWJzWgzOjVLAtflixV4K3TduqzewSA0JoXhqAdg1ygnLt8Nlzio+Ve4gBNspg0n6/v4jwFhdyN32UPdg0f/X4jBjwYsxBLSmJTAEv2/lUtZ31UaKHTmInWn2J8bq1TW2V5litTAkdlbMuq9aC4bLTLF0jKlZpo3ZwMLldm3sbYVKoyKLz4Z+mTXgn3MWAB536Q3ZodEMh00imtLArmbrQc+Oax3YyjaxMIppRX8O0RQznugrtUppZwRANdobt68nGVy9C4qXuux2GDPdQIQ/rAsu2wmRqQ4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
