travis:
  secure:
    BINSTAR_TOKEN: P4xV7F9YK/IziUGz5l7/bkrNtNFNhV7pzDlD69L4E0aalDa0IZTb/1srTuI5JD1LoURMyWn95svmaGUQ2rA3H/nzy0CcpfBeJ4JgoQb0t/JiNQagQqmIMG8hvC4RuDxttAdGmOro4T+Mb/nIxXLeBLMUT9WUQVlbYThqiMqx02S4c8ZZrTDR7R2PLyurPtR4sui5Y3VYquB9EHMVkw8IJezXLG8SKyGMq0ztXjHLPbLG8dUD2ojRg+jBPTpbvafCi+63y0c/2wiOSdq+zCxdjBkfb/IJTKlotx6aZ5yq7kQSmuWXGapRNDSCeElxN8yv+p0TNwPXUlv518HVbZV19jCPSCOuaEZ7ecjzsXJU3rM8n9cEKLZ3YoqccDuQSEEDWGS9fkxYGD5bla960ZhPscLeSX+/Rj0o25KSVLUxiBJJ7jGEfHOBJZd9IEZySx0bpKKqnJo+6PN4kyBoAgKuGTDVyDw0a+D7BXL6/voXmdqsMRZlbKPEHR3LYxJKTi//hJV+zzgJYhjXPgDAF/GRqahe72wI5MmYmJ3FwhxXKnZR/NBAaMFiKqqr1+PMUtacJWLQFJu7dJo0/oHdnZSiotvgcx6Myiykl1TyptU54N7eaDN5RenPVQKtGiBiIbc065bp7Td+qJuboODZA3lQWOElZjyU9MeNnyKEyS6HJOo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
