appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: BO6cS7oOUmzvwQdtUyA9jsCc0QpJ7wtMbIFPgG5aW89y3PXwODGhj2XwL5cF/+k7GdEFiubqC1wf4ayYJ4jgGIA1mVee5F6z3kt9U6yeVNBeBGHY/BGhBoa6tuS2wYrt90ZPoz8YquwJnUdv7O4lhM1ilV8gw6kpsGYIhw9hxqxKFJankQhJKVC0mucZsl9PUI2HgLddIq9G16Hn/XBoph7nxxiyG/mwwQocgZhcKtMq7sUZER8FmyLNt0YLIEhwHhBdEs43hdZAWT/nTuvf6O7oVTsVuUISbXbxZtKg7mtdrE9Y8BjeqjjcwAj7n4tTD2/NSEEeVw6k017qcIJ2Fnb5klhbZ0xjGWNrcpCNMuxENcwoCiLJJHMI838t1ZhyLS27eB6oxxghUbQ84dhDCk6y+OTXLBDkV2ABTZwUAcfMwF0guzSvvD6g8YEXJqZzi+aU9XcJI5GzsCbXWudaZk12yKVk05vKUNt1d/MFAkUDQ3dy12/UWPY/q53nm+cht9mldMFvqTEyT6kqmJ7Lt/aSe3D5118Kb0RXbUSc/iDNFO9cYE3AXfANgDFo55ozra3N8v5TZuFs5mfRoxJrFh8IDFl5wkSddFJwzIg4XlSF9uqWLYXdDybNlr6mnR5aT5SO/ZfjI497d8tFeRGW63JDzH7e9EUXGeK2yxsjMOs=}
